@host=https://localhost:7261

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzMmZjYjQ3MS0zNzkyLTQ0NjgtOTJkMC03NDVkYzI5ZTMxMzEiLCJnaXZlbl9uYW1lIjoiVGhvbWFzIiwiZmFtaWx5X25hbWUiOiJNdWVsbGVyIiwianRpIjoiYTIxNWFjODctMjEyOS00ZDkyLThlNTItZGI3MWM4NjRjNjU2IiwiZXhwIjoxNzMwMjM4NDczLCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.uWaIXrDVHVYyJ0LfyIpKDytHFL8X_PgQ3A1Gmbq1Taw